In [2]:
import pandas as pd
import gzip

def parse(path):
  g = gzip.open(path, 'rb')
  for l in g:
    yield eval(l)

def getDF(path):
  i = 0
  df = {}
  for d in parse(path):
    df[i] = d
    i += 1
  return pd.DataFrame.from_dict(df, orient='index')

df = getDF('metadata.json.gz')

In [4]:
df['price'] = df['price'].fillna(0)

In [5]:
df.head()

asin                 salesRank  \
0  0001048791        {'Books': 6334800}   
1  0000143561   {'Movies & TV': 376041}   
2  0000037214     {'Clothing': 1233557}   
3  0000032069                       NaN   
4  0000031909  {'Toys & Games': 201847}   

                                               imUrl  \
0  http://ecx.images-amazon.com/images/I/51MKP0T4...   
1  http://g-ecx.images-amazon.com/images/G/01/x-s...   
2  http://ecx.images-amazon.com/images/I/31mCncNu...   
3  http://ecx.images-amazon.com/images/I/51EzU6qu...   
4  http://ecx.images-amazon.com/images/I/41xBoP0F...   

                                          categories  \
0                                          [[Books]]   
1                            [[Movies & TV, Movies]]   
2  [[Clothing, Shoes & Jewelry, Girls], [Clothing...   
3  [[Sports & Outdoors, Other Sports, Dance, Clot...   
4         [[Sports & Outdoors, Other Sports, Dance]]   

                                               title  \
0  The Crucible: Performed by Stuart Pankin, Jero...   
1  Everyday Italian (with Giada de Laurentiis), V...   
2  Purple Sequin Tiny Dancer Tutu Ballet Dance Fa...   
3                     Adult Ballet Tutu Cheetah Pink   
4                        Girls Ballet Tutu Neon Pink   

                                         description  price  \
0                                                NaN   0.00   
1  3Pack DVD set - Italian Classics, Parties and ...  12.99   
2                                                NaN   6.99   
3                                                NaN   7.89   
4  High quality 3 layer ballet tutu. 12 inches in...   7.00   

                                             related       brand  
0                                                NaN         NaN  
1  {'also_viewed': ['B0036FO6SI', 'B000KL8ODE', '...         NaN  
2  {'also_viewed': ['B00JO8II76', 'B00DGN4R1Q', '...  Big Dreams  
3  {'also_bought': ['0000032050', 'B00D0DJAEG', '...    BubuBibi  
4  {'also_bought': ['B002BZX8Z6', 'B00JHONN1S', '...     Unknown

In [6]:
x = df[df['asin']=='0000032069']['related']

In [7]:
x

3    {'also_bought': ['0000032050', 'B00D0DJAEG', '...
Name: related, dtype: object

In [8]:
x.head()

3    {'also_bought': ['0000032050', 'B00D0DJAEG', '...
Name: related, dtype: object

In [9]:
x.iloc[0]['also_bought']

['0000032050',
 'B00D0DJAEG',
 '0000032042',
 'B00D0F450I',
 'B00D2JTMS2',
 'B00D0FDUAY',
 'B00D2JSRFQ',
 '0000032034',
 'B00D0D5F6S',
 'B00D2JRWWA',
 'B00D0FIIJM',
 'B00D0FCQQI',
 'B00EXVN9PU',
 'B0041EOTJO',
 'B004PYEE8G',
 'B001GTKPDQ',
 'B00EON0SJ2',
 'B005HMHOQ4',
 'B002XZMGGQ']

In [18]:
x.iloc[0]['also_viewed']

['B00D0F450I',
 '0000032050',
 'B00D2JTMS2',
 '0000032042',
 'B004PYEE8G',
 'B00JHNSNSM',
 'B00D0DJAEG',
 'B00D2JSRFQ',
 'B00D0FCQQI',
 'B00D2JRWWA',
 'B003AVNY6I',
 'B0071KR2LC',
 'B00GOR07RE',
 'B00D0FIIJM',
 'B005F50FXC',
 'B0079MCIMU',
 'B00D0FDUAY',
 'B00H3RYN3I',
 'B005C4Y4F6',
 'B007IEFT84',
 'B00D0D5F6S',
 'B002BZX8Z6',
 'B00JHONN1S',
 'B008F0SU0Y',
 'B00FNNFXAG',
 'B007R2RM8W',
 'B007VM3AMK',
 'B00C0PLENA',
 'B00BJGG6VG',
 'B00E1YRI4C',
 'B00IIK61WA',
 'B009UC638W',
 'B00KZN6RVI',
 'B00CSFEENY',
 'B002GZGI4E',
 'B00HSOJJ94',
 'B00LIPP4VG',
 'B009RXWNSI',
 'B00E87F196',
 'B005HMHOQY',
 'B00J6S9MSS',
 '0000032034',
 'B00CJQGNJK',
 'B008FCA0F0',
 'B0056LG7GY',
 'B00DPQWCZ2',
 'B00I3PV0US',
 'B00KZN6IVW',
 'B0054TBWKO',
 'B00I2S01I8',
 'B00BXF12P8',
 'B00GVHU678',
 'B005NWENGC',
 'B003AVKOP2',
 'B00JK8MQ4Q',
 'B00FZIMVQS',
 'B008BB19VE',
 'B00GTEXPOE',
 'B009WPT2RQ',
 'B00E37SBBG']

In [16]:
df_related = df[['asin','related']]

In [19]:
df_related.columns

Index(['asin', 'related'], dtype='object')

In [22]:
df_related = df_related[df_related['related'].notnull()]

In [31]:
'also_viewed' in df_related.iloc[0]['related'].keys()

True

In [32]:
df_related.iloc[0]['related']['also_viewed']

['B0036FO6SI',
 'B000KL8ODE',
 '000014357X',
 'B0037718RC',
 'B002I5GNVU',
 'B000RBU4BM']

In [34]:
df_related.shape

(6691673, 2)

In [35]:
df.shape

(9430088, 9)

In [38]:
# building the also viewed network
with open('also_viewed_network.csv','w') as ft:
    for i in range(df_related.shape[0]):
        u = df_related.iloc[i]['asin']
        if 'also_viewed' in df_related.iloc[i]['related'].keys():
            for v in df_related.iloc[i]['related']['also_viewed']:
                ft.write(u+','+v)
                ft.write('\n')    
        

In [39]:
import numpy as np

In [42]:
a = np.zeros((2,4))

In [43]:
b = np.ones((1,4))

In [46]:
a[0] = a[0]+b

In [47]:
a

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [50]:
db_net = pd.read_csv('also_viewed_network.csv',names=['F','T'])

In [51]:
db_net.columns

Index(['F', 'T'], dtype='object')

In [63]:
products = db_net['F'].unique()

In [64]:
len(products)

4021458

In [68]:
nbr_count = np.random.randint(1,10,(10))

In [73]:
nbr_count.shape[0]

10

In [74]:
nbrs = np.zeros((nbr_count.shape[0],np.max(nbr_count)))

In [77]:
for i in range(nbr_count.shape[0]):
    for j in range(nbr_count[i]):
        nbrs[i,j] = np.random.randint(1,10)
nbrs        

array([[6., 3., 7., 5., 1., 6., 2., 4., 3.],
       [6., 4., 0., 0., 0., 0., 0., 0., 0.],
       [1., 4., 1., 6., 4., 0., 0., 0., 0.],
       [9., 5., 6., 8., 7., 0., 0., 0., 0.],
       [2., 1., 1., 5., 1., 0., 0., 0., 0.],
       [5., 4., 4., 4., 6., 3., 0., 0., 0.],
       [8., 0., 0., 0., 0., 0., 0., 0., 0.],
       [7., 2., 7., 4., 4., 0., 0., 0., 0.],
       [2., 3., 5., 7., 4., 9., 0., 0., 0.],
       [5., 5., 1., 6., 9., 6., 3., 0., 0.]])

In [78]:
nbrs[0,0]=9

In [79]:
nbrs[0,1]=8

In [88]:
nbrs[9,1]=8
nbrs[9,3]=4
nbrs

array([[9., 8., 7., 5., 1., 6., 2., 4., 3.],
       [6., 4., 0., 0., 0., 0., 0., 0., 0.],
       [1., 9., 7., 6., 8., 0., 0., 0., 0.],
       [1., 5., 9., 8., 6., 0., 0., 0., 0.],
       [2., 7., 4., 5., 1., 0., 0., 0., 0.],
       [5., 4., 7., 9., 6., 3., 0., 0., 0.],
       [8., 0., 0., 0., 0., 0., 0., 0., 0.],
       [7., 2., 8., 5., 4., 0., 0., 0., 0.],
       [2., 3., 5., 7., 4., 9., 0., 0., 0.],
       [5., 8., 1., 4., 9., 6., 3., 0., 0.]])

In [91]:
%load_ext Cython
from cython.parallel import prange
#cython: boundscheck=False, wraparound=False, nonecheck=False

The Cython extension is already loaded. To reload it, use:
  %reload_ext Cython


In [90]:
walks = np.zeros((100,10))

In [101]:
%%cython

def generateWalks(nbrs,nbr_count,walks):
    #walks = np.zeros((100,10))
    cdef int w_c = 100
    cdef int w_l = 10
    for i in prange(w_c,nogil=True):
        start = np.random.randint(1,9)
        walk = np.zeros(10)
        walk[0] = start
        for j in range(1,w_l):
            walk[j] = np.random.choice(nbrs[start,:nbr_count[start]])
            start = walk[j]
            
    return walks        


Error compiling Cython file:
------------------------------------------------------------
...

def generateWalks(nbrs,nbr_count,walks):
    #walks = np.zeros((100,10))
    cdef int w_c = 100
    cdef int w_l = 10
    for i in prange(w_c,nogil=True):
            ^
------------------------------------------------------------

/Users/sandipansikdar/.ipython/cython/_cython_magic_166245a50a66ce196599982fb89013aa.pyx:6:13: undeclared name not builtin: prange

Error compiling Cython file:
------------------------------------------------------------
...
def generateWalks(nbrs,nbr_count,walks):
    #walks = np.zeros((100,10))
    cdef int w_c = 100
    cdef int w_l = 10
    for i in prange(w_c,nogil=True):
        start = np.random.randint(1,9)
               ^
------------------------------------------------------------

/Users/sandipansikdar/.ipython/cython/_cython_magic_166245a50a66ce196599982fb89013aa.pyx:7:16: undeclared name not builtin: np


TypeError: object of type 'NoneType' has no len()

In [98]:
np.random.choice(nbrs[2,:nbr_count[2]])

7.0